### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by weberc2** [lunarway/postgresql-controller#81]
Hello, I would like to use this project in my hobby Raspberry Pi cluster. Would you be interested in accepting a PR to add ARM support?

**Comment by Crevil** [comment]
Sure thing 🙌

**Comment by Crevil** [comment]
There is now a release v0.1.1 with ARM support. Thank you @weberc2 

https://quay.io/repository/lunarway/postgresql-controller?tab=tags
